[versions]
jmh = "1.37"


[libraries]
# org.openjdk.jmh - Java Microbenchmark Harness
# https://github.com/openjdk/jmh
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }


[plugins]
# me.champeau.jmh - JMH Gradle Plugin
# https://github.com/melix/jmh-gradle-plugin
jmh = { id = "me.champeau.jmh", version = "0.7.3" }
